"""updated appointments model

Revision ID: 4f4d3da27a8c
Revises: 
Create Date: 2024-10-21 11:19:33.294749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4d3da27a8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dentist_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['dentist_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dentist_id')

    # ### end Alembic commands ###
